app/site/views.py
from flask import Blueprint, request, render_template, redirect, url_for, current_app
from flask_login import current_user
from .models import Meal, Ingrediant, Measure, Ammount, User
from .forms import BigForm, SettingForm, LoginForm, SignupForm
from sqlalchemy.sql.expression import func
from .. import login_manager, bcrypt
from flask_login import current_user, login_required, login_user, logout_user, confirm_login, fresh_login_required
from .. import db

main = Blueprint("main", __name__)


@main.route('/')
def about():
    return render_template('about.html')


@main.route('/test')
def test():
    return redirect(url_for('main.calendar', days='2', meal='1', breakfast='001002'))


@main.route('/settings/', methods=['GET', 'POST'])
def settings():
    form = SettingForm()
    if form.validate_on_submit():

        days = int(form.days.data)

        bin_meal_num = 0
        if form.breakfast.data:
            bin_meal_num += 1
        if form.lunch.data:
            bin_meal_num += 2
        if form.dinner.data:
            bin_meal_num += 4

        breakfast = ''
        lunch = ''
        dinner = ''

        if form.breakfast.data:
            meal = Meal.query.filter(Meal.breakfast.is_(True)).order_by(func.rand()).limit(days).all()
            for m in meal:
                breakfast += (str(m.id).zfill(3))
        if form.lunch.data:
            meal = Meal.query.filter(Meal.lunch.is_(True)).order_by(func.rand()).limit(days).all()
            for m in meal:
                lunch += (str(m.id).zfill(3))
        if form.dinner.data:
            meal = Meal.query.filter(Meal.dinner.is_(True)).order_by(func.rand()).limit(days).all()
            for m in meal:
                dinner += (str(m.id).zfill(3))
        return redirect(url_for('main.calendar',
                                days=days,
                                meal=bin_meal_num,
                                breakfast=breakfast,
                                lunch=lunch,
                                dinner=dinner))

    return render_template('settings.html', form=form, current_user=current_user)


@main.route('/calendar/')
def calendar():
    if request.args.get('days'):
        days = int(request.args.get('days'))
        meal_arg = int(request.args.get('meal'))

        dictionary = {'breakfast': request.args.get('breakfast'),
                      'lunch': request.args.get('lunch'),
                      'dinner': request.args.get('dinner')}

        meal_list = {'breakfast': [],
                     'lunch': [],
                     'dinner': []}

        meal_key = {'breakfast': 0x1,
                    'lunch': 0x2,
                    'dinner': 0x4}

        y = [k for k, v in meal_key.items() if meal_arg & v == v]
        for m in y:
            if m in dictionary:
                g = dictionary.get(m)
                meal_list[m] = break_list(str(g), days)

        ingrediants = []

        #query the database
        breakfast_meals = Meal.query.filter(Meal.id.in_(meal_list['breakfast'])).all()
        lunch_meals = Meal.query.filter(Meal.id.in_(meal_list['lunch'])).all()
        dinner_meals = Meal.query.filter(Meal.id.in_(meal_list['dinner'])).all()

        breakfast_dic = {'name': "Breakfast", 'data': breakfast_meals}
        lunch_dic = {'name': "Lunch", 'data': lunch_meals}
        dinner_dic = {'name': "Dinner", 'data': dinner_meals}

        meals = [breakfast_dic, lunch_dic, dinner_dic]

        # get the ingredients into the ingredients list
        for meal_list in meals:
            if meal_list['data']:
                for each in meal_list['data']:
                    ingrediant = db.engine.execute(
                        "SELECT ingrediant.name, ammount.ammount, measure.unit "
                        "FROM ammount "
                        "INNER JOIN ingrediant "
                        "ON ammount.ing_id=ingrediant.id "
                        "INNER JOIN measure "
                        "ON ammount.measure_id=measure.id "
                        "WHERE ammount.meal_id=" + str(each.id) + ";")
                    for ing in ingrediant:
                        i = {'name': ing.name, 'ammount': ing.ammount, 'unit': ing.unit}
                        ingrediants.append(i)

        ingrediants.sort(key=lambda x: (x['name'], x['unit']))
        for _ in range(days):
            for i in range((len(ingrediants))):
                try:
                    if ingrediants[i]['name'] == ingrediants[i + 1]['name'] and \
                                    ingrediants[i]['unit'] == ingrediants[i + 1]['unit']:
                        number = int(ingrediants[i]['ammount']) + int(ingrediants[i + 1]['ammount'])
                        ingrediants[i]['ammount'] = number
                        ingrediants.pop(i+1)
                except IndexError:
                    pass
        percent = (100/days)

        return render_template('calendar.html',
                               meals=meals,
                               ingrediants=ingrediants,
                               current_user=current_user,
                               percent=percent,
                               days=days)
    else:
        days = 7
        meal_arg = 4

        dinner = ""

        meal = Meal.query.filter(Meal.dinner.is_(True)).order_by(func.rand()).limit(days).all()
        for m in meal:
            dinner += (str(m.id).zfill(3))

        return redirect(url_for('main.calendar',
                                days=days,
                                meal=meal_arg,
                                dinner=dinner))


@main.route('/meal/')
def meal():
    num = request.args.get('meal')
    meal = Meal.query.get(num)
    ingrediants = []
    # ingrediant = Ammount.query.join(Ingrediant, Ammount.ing_id == Ingrediant.id )
    # .join(Measure, Ammount.measure_id == Measure.id).filter(Ammount.meal_id == meal.id )
    ingrediant = db.engine.execute("SELECT ingrediant.name, ammount.ammount, measure.unit "
                                   "FROM ammount "
                                   "INNER JOIN ingrediant "
                                   "ON ammount.ing_id=ingrediant.id "
                                   "INNER JOIN measure "
                                   "ON ammount.measure_id=measure.id "
                                   "WHERE ammount.meal_id=" + str(meal.id) + ";")
    for ing in ingrediant:
        ingrediants.append(ing)
    ingrediants.sort(key=lambda x: x.name)
    return render_template('meal.html',
                           meal=meal,
                           ingrediants=ingrediants,
                           current_user=current_user)


@main.route('/insert/', methods=["GET", "POST"])
@login_required
def insert():
    form = BigForm()
    if form.validate_on_submit():
        print "validation succeessful"
        meal = Meal()
        meal.name = form.name.data
        meal.instructions = form.instructions.data
        meal.breakfast = form.breakfast.data
        meal.lunch = form.lunch.data
        meal.dinner = form.dinner.data
        db.session.add(meal)
        db.session.commit()
        for i in range(11):
            if form.ingrediants[i].data:
                try:
                    ing = Ingrediant()
                    dbing = Ingrediant.query.filter(Ingrediant.name.like(form.ingrediants[i].data)).first()
                    if dbing:
                        ing = dbing
                    else:
                        ing.name = form.ingrediants[i].data
                        db.session.add(ing)
                        db.session.commit()

                    meas = Measure.query.filter(Measure.unit.like(form.measurements[i].data)).first()

                    amnt = Ammount()
                    amnt.meal_id = meal.id
                    amnt.ammount = form.ammounts[i].data
                    amnt.measure_id = meas.id
                    amnt.ing_id = ing.id
                    db.session.add(amnt)
                    db.session.commit()
                except IndexError:
                    pass
            else:
                break
        return redirect(url_for('main.about'))

    return render_template('insert.html',
                           form=form,
                           current_user=current_user)


@main.route('/profile/')
def profile():
    return render_template("profile.html",
                           current_user=current_user)


@login_required
@main.route('/measure/')
def measure():
    if current_user.admin:
        example_list = ['Gallon', 'Litre', 'Pint', 'Cup', 'Fluid ounce',
                        'Pound', 'ounce', 'Table spoon', 'Tea spoon',
                        'Inch', 'Centimeter', 'Milliliter', 'Piece', 'Dozen']
        for i in example_list:
            meas = Measure()
            meas.unit = i
            db.session.add(meas)
            db.session.commit()
        return redirect(url_for('main.about'))
    return redirect(url_for('main.about'))

############################################
# Login Manager
############################################


@login_manager.unauthorized_handler
def unauthorized_callback():
    return redirect('/login')


@login_manager.user_loader
def user_loader(user_id):
    """Given *user_id*, return the associated User object.

    :param unicode user_id: user_id (email) user to retrieve
    """
    return User.query.get(user_id)


@main.route('/register', methods=["get", "POST"])
def register():
    form = SignupForm()
    if form.validate_on_submit():
        user = User()
        form.populate_obj(user)
        pw_hash = bcrypt.generate_password_hash(form.password.data)
        user.password = pw_hash
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('main.login'))
    return render_template('register.html', form=form, current_user=current_user)


@main.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():

app/templates/about.html
{% extends 'base.html' %}

{% block body %}
	<!-- Header -->
	<header class="w3-container w3-blue w3-center w3-padding-128">
		<div class="anim"></div>
		<h1 class="w3-jumbo no-margin head">MEAL MAKER</h1>
		<div class="anim" style=" margin-top: 4px; "></div>
		<p class="w3-xlarge">Template by w3.css</p>
		<a href="/calendar">
			<button class="w3-btn w3-padding-16 w3-large w3-margin-top">Get Started</button>
		</a>
	</header>

	<!-- First Grid -->
	<div class="container">
		<div class="w3-row-padding w3-padding-64 w3-container">
			<div class="w3-content">
				<div class="w3-twothird">
					<h1>Lorem Ipsum</h1>
					<h5 class="w3-padding-32">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</h5>

					<p class="w3-text-grey">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint
		occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
		laboris nisi ut aliquip ex ea commodo consequat.</p>
				</div>

				<div class="w3-third w3-center">
					<i class="fa fa-anchor w3-padding-64 w3-text-red"></i>
				</div>
			</div>
		</div>

		<!-- Second Grid -->
		<div class="w3-row-padding w3-light-grey w3-padding-64 w3-container">
			<div class="w3-content">
				<div class="w3-third w3-center">
					<i class="fa fa-coffee w3-padding-64 w3-text-red w3-margin-right"></i>
				</div>

				<div class="w3-twothird">
					<h1>Lorem Ipsum</h1>
					<h5 class="w3-padding-32">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</h5>

					<p class="w3-text-grey">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint
		occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
		laboris nisi ut aliquip ex ea commodo consequat.</p>
				</div>
			</div>
		</div>

		<div class="w3-container w3-black w3-center w3-opacity w3-padding-64">
			<h1 class="w3-margin w3-xlarge">Quote of the day: live life</h1>
		</div>
	</div>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html>
    <title>Meal Maker</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lato">

    <link rel='stylesheet' href="/static/css/custom.css">
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
       
    <body>
    	<ul class="w3-navbar w3-border w3-light-grey w3-top mobile">
    		<li class="w3-dropdown-click ">
    			<a onclick="myFunction()" href="javascript:void(0)">
    				<span class="">Meal Maker</span>
    				<span class="obj-right mobile-btn"><i class="fa fa-bars "></i></span>
    			</a>
				<div id="demo" class="w3-dropdown-content w3-border">
					<a class="w3-hover-grey" href="">Home</a>
					<a class="w3-hover-grey" href="">Settings</a>
					<a class="w3-hover-grey" href="/calendar">Calendar</a>
					<a class="w3-hover-grey" href="/insert">Insert</a>
				</div>
			</li>
		</ul>

		<ul class="w3-navbar w3-border w3-light-grey w3-top topnav">
			<li><a class="" href="/">Meal Maker</a></li>
			<li><a class="w3-hover-grey" href="/">Home</a></li>
			<li><a class="w3-hover-grey" href="/settings">Settings</a></li>
			<li><a class="w3-hover-grey" href="/calendar">Calendar</a></li>
			{% if current_user.authenticated: %}
				<li><a class="w3-hover-grey" href="/insert">Insert</a></li>
				<li class="w3-right"><a class=" w3-hover-grey" href="/logout">Logout</a></li>
				<li class="w3-right"><a class="w3-hover-grey"> Hello {{ current_user.email }}</a></li>
			{% else: %}
				<li class="w3-right"><a class=" w3-hover-grey" href="/register">Register</a></li>
				<li class="w3-right"><a class=" w3-hover-lightgrey" href="/login">Login</a></li>
			{% endif %}
		</ul>
        
		
        <!-- !PAGE CONTENT! -->
        

        {% block body %}
        {% endblock %}

		
        <!-- Footer -->
        <footer class="w3-container w3-padding-64 w3-light-grey w3-center w3-opacity w3-xlarge w3 row" style="margin-top:128px"> 
        	<div class="w3-col s12 m4 l3 text-left info">
        	</div>
        	<div class="w3-col s12 m4 l6 w3-center">
			</div>
			</div class="w3-col s12 m4 l3">
				<a href=""><button class="w3-btn w3-padding-16 w3-large w3-margin-top">Manage</button></a>
				<a href=""> <button class="w3-btn w3-padding-16 w3-large w3-margin-top">Register</button></a>
			</div>
			
        </footer>
         
        <script>        
        function myFunction() {
			var x = document.getElementById("demo");
			if (x.className.indexOf("w3-show") == -1) {
				x.className += " w3-show";
			} else { 
				x.className = x.className.replace(" w3-show", "");
			}
		}
        </script>
    </body>
</html>

app/templates/calendar.html
{% extends 'base.html' %}


{% block body %}
	<div class="container">
	<br />
		<div style="background-color: #f8f8f8;">
		 	{% for meal_list in meals: %}
				<div class="w3-row" id="{{meal_list['name']}}">
					{% if meal_list['data']: %}
						<div class="w3-col w3-container w3-green centered" style="width:100%"><p>{{meal_list['name']}}</p></div>
					{% endif %}
					<div class="center centered">
						{% for meal in meal_list['data']: %}
							<div class="w3-col w3-card-4" style="width: calc({{percent}}% - 10px); margin: 5px;">
								<a href="{{ url_for('main.meal', meal=meal.id ) }}">
									<header class="w3-container w3-blue">
										<h4>{{meal.name}}</h4>
									</header>
									<div class="w3-container bg-white">
										<p>Lorem ipsum...</p>
									</div>
								</a>
							</div>
						{% endfor %}
					</div>
				</div>
			{% endfor %}
		</div>
		 <hr/>
		 <table class="w3-table w3-striped w3-border">
		 	<tr>
		 		<th class="centered">Ingrediant</th>
		 		<th class="centered">Quantity</th>
		 		<th class="centered">Unit</th>
		 	</tr>	
		 	{% for ing in ingrediants: %}
		 		<tr>
		 			<td class="centered">{{ ing['name'] }}</td>
		 			<td class="centered">{{ ing['ammount'] }}</td>
		 			<td class="centered">{{ ing['unit'] }}<td>
		 		</tr>
		 	{% endfor %}
		 </table>
		 <div class="">
		 	{% if current_user.authenticated: %}
		 	{% endif %}
		 </div>
	 </div>
{% endblock %}

app/templates/insert.html
{% extends 'base.html' %}
{% from "macros.html" import render_field %}


{% block body %}
	<div class="container">
		<div class="w3-card-4 c-card">
			<div class="w3-container w3-brown">
			  	<h2>Insert a Meal</h2>
			</div>
			<form class="w3-container block-center" method='POST' action='/insert/' enctype="multipart/form-data" >
				<dl>
					{{ form.csrf_token() }}
					<div class="center">
						<dd >
						 	<label class="w3-label w3-validate" for="name">Name: </label> 
						 	<input class="w3-input w3-border w3-light-grey" id="name" name="name" type="text" value="" required>
						</dd>
						<dd >
							<label class=" w3-label w3-validate" for="instructions">Instructions: </label> 
							<textarea id="instructions" name="instructions" required ></textarea>  
						</dd >
						<div class="w3-row-padding">
							<div class="w3-col l4 m4 center">
								<dd>
									<label for="breakfast">Breakfast: </label> 
									<input id="breakfast" name="breakfast" type="checkbox" value="y">  
								</dd>
							</div>
							<div class="w3-col l4 m4 center">
								<dd>
									<label for="lunch">Lunch: </label> 
									<input id="lunch" name="lunch" type="checkbox" value="y">
								</dd>
							</div>
							<div class="w3-col l4 m4 center">
								<dd>
									<label for="dinner">Dinner: </label> 
									<input id="dinner" name="dinner" type="checkbox" value="y">
		  						 </dd>
		  					</div>
	  					</div>
						<div class="w3-row-padding">
							<dd>
								{% for i in range(10)%}
									<div class="w3-row-padding row{{i}}" id="row{{i}}">
										<div class="w3-col l4 m4">
											<input class="w3-input w3-border w3-light-grey" id="ingrediants-{{ i }}" name="ingrediants-{{ i }}" type="text" value="" placeholder="Ingrediant">
										</div>
									
										<div class="w3-col l4 m4"> 
											<input class="w3-input w3-border w3-light-grey w3-validate" id="ammounts-{{ i }}" name="ammounts-{{ i }}" type="text" value="" placeholder="Quantity">
										</div>
									
										<div class="w3-col l3 m3">
											<select class="w3-select w3-border" id="measurements-{{ i }}" name="measurements-{{ i }}">
												<option value="" disabled selected>Measurement</option>
												<option value="Gallon">Gallon</option>
												<option value="Litre">Litre</option>
												<option value="Milliliter">Milliliter</option>
												<option value="Pint">Pint</option>
												<option value="Cup">Cup</option>
												<option value="Fluid ounce">Fluid ounce</option>
												<option value="Pound">Pound</option>
												<option value="ounce">ounce</option>
												<option value="Table spoon">Table spoon</option>
												<option value="Tea spoon">Tea spoon</option>
												<option value="Inch">Inch</option>
												<option value="Centimeter">Centimeter</option>
												<option value="Piece">Piece</option>
												<option value="Dozen">Dozen</option>
											</select>
										</div>
										<div class="w3-col l1 m1">
											<button class="w3-btn" id="btn{{ i }}" style="width: 100%; height: 100%;" onclick="" type="button">Add</button>
										</div>
									</div>
								{% endfor %}
							</dd>
						</div>
						<dd>
							<br />
							<input class="w3-btn" id="submit" name="submit" type="submit" value="Submit" style="width: 100%;">	
						</dd>
					</div>
				</dl>
			</form>
		</div>
	</div>
	<script>
	$(document).ready(function(){
		{% for i in range(10): %}
			$("#btn{{i}}").click(function(){
				$("#row{{ i + 1 }}").removeClass("row{{ i + 1}}");
				$("#btn{{i}}").addClass("row1");
			});
		{% endfor %}
	});
	</script>
{% endblock %}

app/templates/list.html
{% extends 'base.html' %}


{% block body %}

{% endblock %}

app/templates/login.html
{% extends 'base.html' %}
{% from "macros.html" import render_field %}

{%  block body %}
<div class="w3-content" style="max-width:1000px">
	<div class="w3-card-4 c-card ">
		<div class="w3-container w3-brown">
		  	<h2>Login</h2>
		</div>
		<form class="w3-container block-center" method='POST' action='/login' enctype="multipart/form-data" style=" max-width: 600px;">
			<dl>
				{{ form.csrf_token() }}
				<dt>
					<label for="email">Email Address: </label>
				</dt>
				<dd class="">
					<label for="email">Email Address: </label>
					<input id="email" name="email" value="" type="text">
				</dd>
				<dt>
					<label for="password">Password: </label>
				</dt>
				<dd class="">
					<label for="password">Password: </label>
					<input id="password" name="password" value="" type="password">
				</dd>
				
			</dl>
			{{ render_field(form.submit) }}
		</form>
	</div>
</div>
{% endblock %}

app/templates/macros.html
{% macro render_field(field) %}
  <dd>{{ field.label }} {{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

app/templates/meal.html
{% extends 'base.html' %}


{% block body %}
	<div class="container">
		<br />
		<div class="w3-card">
			<header class="w3-container  w3-blue">
				<h1>{{ meal.name }}</h1>
			</header>
			<div class="w3-container w3-row">
				<div class="w3-col l8">
					<pre>{{ meal.instructions }}</pre>
				</div>
				<div class="w3-col l4">
					<table class="w3-table w3-striped ">
					<tr>
						<th class="centered">Ingrediant</th>
						<th class="centered">Quantity</th>
						<th class="centered">Unit</th>
					</tr>
					{% for ing in ingrediants: %}
						<tr>
							<td class="centered">{{ ing.name }}</td>
							<td class="centered">{{ ing.ammount }}</td>
							<td class="centered">{{ ing.unit }}<td>
						</tr>
					{% endfor %}
					</table>
				</div>
			</div>
		</div>
		<hr/>
		
	 </div>
{% endblock %}

app/templates/register.html
{% extends 'base.html'  %}
{% from "macros.html" import render_field %}

{% block body %}
<div class="w3-content" style="max-width:1000px">
	<div class="w3-card-4 c-card ">
		<div class="w3-container w3-brown">
		  	<h2>Register a new user</h2>
		</div>
		  <div class="row">
		<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
		  <form action="" method="POST" role="form">
		  	{{ form.csrf_token }}
		    <legend>Register a new user</legend>
		  
		    <div class="form-group">
		      <label for="">Email:</label>
		      <input type="email" id="email" name="email" required="required" class="form-control" placeholder="Email">
		    </div>

		    <div class="form-group">
		      <label for="">Password:</label>
		      <input type="password" name="password" id="password" class="form-control" required="required" title="">
		    </div>
		    
		    <div class="form-group">
		      <label for="">Repeat Password:</label>
		      <input type="password" name="confirm" id="confirm" class="form-control" required="required" title="">
		    </div>
		    
		  
		    <button type="submit" class="btn btn-primary">Register</button>
		  </form>
		</div>
	  </div>

	</div>
</div>

{% endblock %}

app/templates/settings.html
{% extends 'base.html' %}
{% from "macros.html" import render_field %}


{% block body %}
	<div class="container">
		<div class="w3-card-4 c-card">
			<div class="w3-container w3-brown">
			  	<h2>What kind of meal</h2>
			</div>
			<form class="w3-container block-center" method='POST' action='/settings/' enctype="multipart/form-data" >
				<dl>
					{{ form.csrf_token() }}
					<div class="center">
						{{ render_field(form.days) }}
						{{ render_field(form.breakfast) }}
						{{ render_field(form.lunch) }}
						{{ render_field(form.dinner) }}
						<input class="w3-btn" id="submit" name="submit" type="submit" value="Submit" style="width: 100%;">	
					</div>
				</dl>
			</form>
		</div>
	</div>
{% endblock %}

app/templates/view.html
{% extends 'base.html' %}


{% block body %}

{% endblock %}